name: Build and Deploy

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: write

jobs:
  build-and-deploy:
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v4
    
        - name: Use Node.js 
          uses: actions/setup-node@v3
          with:
            node-version: "16.x"
    
        - name: Install dependencies
          run: npm install
    
        - name: Build the project
          run: npm run build
    
        - name: Deploy to GitHub Pages
          if: github.ref == 'refs/heads/develop'
          uses: JamesIves/github-pages-deploy-action@v4.4.3
          with:
            branch: gh-pages
            folder: dist 
            token: ${{ secrets.GITHUB_TOKEN }}
            clean: true  
